### ISSUE TITLE
Can you add a link for the overrides? 

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/ai-rag-chat-evaluator#27]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

I can't find a list to the overrides. I looked in azure-search-openai-demo as well. I'm adding screenshots of what I did find. 

<img width="307" alt="image" src="https://github.com/Azure-Samples/ai-rag-chat-evaluator/assets/41597107/3b32fdd5-7344-4264-9fe2-0aaba30552e2">

https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/customization.md

<img width="350" alt="image" src="https://github.com/Azure-Samples/ai-rag-chat-evaluator/assets/41597107/c30d9f90-cceb-48ed-94e0-18e0cb1f76a3">

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
The overrides are specific to the protocol and/or repository, so I don't think it should be documented here. I've added a link to the protocol from this readme now.
I also intend to use QuartSchema with Pydantic models in the Python repo to document the request/response schema there. Closing the issue here, feel free to file one in Python repo to track that.
